### ISSUE TITLE
/user/pointshop, /popular 페이지 개발

### ISSUE THREAD

**Issue by minchan02** [osamhack2022-v2/WEB_AI_MILIROUTINE_MILIROUTINE#6]
- [x] /user/pointshop
- [x] /popular

남은 두개 페이지 개발하고 여태까지 짠 코드들 디버깅하면서 코드 리뷰 진행하겠습니다.

**Comment by minchan02** [comment]
@yoopark 혹시 routine순위는 어떤 기준으로 매기나요??

**Comment by yoopark** [comment]
처음 생각은 조회수 순이었는데, 조회수 정보가 없어서 일단 참여자순으로 해야 할 것 같습니다.

**Comment by minchan02** [comment]
네 알겠습니다
