### ISSUE TITLE
user/setting 페이지 작업

### ISSUE THREAD

**Issue by silverttthin** [osamhack2022-v2/WEB_AI_MILIROUTINE_MILIROUTINE#9]
- [x] SideNavbar 컴포넌트 작성 -> 버튼과는 다르게 미클릭시 배경색이 없어서 따로 만들어야할듯
- [x] 페이지 작업 착수

- [ ] setting/pw 페이지 작업

**Comment by yoopark** [comment]
제가 만들었습니다~~ 하하..
